Utnyttelsesgrad/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Utnyttelsesgrad.Areas.HelpPage.ModelDescriptions;
using Utnyttelsesgrad.Areas.HelpPage.Models;

namespace Utnyttelsesgrad.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Utnyttelsesgrad/Views/Shared/_Layout.cshtml
@using KommIT.FIKS.AdapterAltinnSvarUt.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        <div class="mainmenu row">
            <div class="headerlogo col-sm-6 pull-left">
                <div class="pull_logo">
                    <a title="Til startsiden" href="/">
                        <img title="Til startsiden" src="/Content/images/dibk_logo.png" alt="Til startsiden" style="border-width:0px;">
                    </a>
                </div>
                <p class="sitetitle">

                </p>
            </div>

            <div class="container col-sm-6 menulist">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <div class="navbar-collapse collapse">
                    <ul class="pull-right">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </div>
            </div>

            <div class="clearfix"></div>
        </div>
        @RenderBody()
    </div>

    <div class="container body-content container-footer">
        <footer>
            <div class="row">
                <div class="col-sm-4 footertext">
                    <p>
                        <strong>KONTAKT OSS</strong>
                    </p>
                    <ul>
                        <li><a href="http://dibk.no/no/Systemside/HeaderMenu/Kontakt-oss/">Kontakt DIBK</a></li>
                        <li>E-post: <a style="font-size: 1em; line-height: 1em;" title="Henvendelser om fortolkning av regelverk og generelle spørsmål kan rettes til post@dibk.no" href="mailto:post@dibk.no">post@dibk.no</a></li>
                        <li>Byggsøk: <a style="font-size: 1em; line-height: 1em;" title="Spørsmål om Byggsøk? Send en epost til brukerstøtte" href="mailto:byggsok@dibk.no">byggsok@dibk.no</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 footertext">
                    <p><strong>KONTAKTPERSON FOR DIBK</strong></p>
                    <ul>
                        <li>Olaug Hana Nesheim</li>
                        <li>Telefon: +47 93 05 66 35</li>
                        <li>E-post: <a href="mailto:ohn@dibk.no">ohn@dibk.no</a></li>
                    </ul>

                </div>
                <div class="col-sm-4 footertext">
                    <p><strong>KONTAKTPERSON FOR ARKITEKTUM AS</strong></p>
                    <ul>
                        <li>Tor Kjetil Nilsen</li>
                        <li>Telefon: +47 48 14 84 68</li>
                        <li>E-post: <a href="mailto:tor@arkitektum.no">tor@arkitektum.no</a></li>
                    </ul>
                </div>
            </div>
            <hr />
            <div class="margin-top">
                <p class="pull-right">Versjon: @Html.ApplicationVersionNumber()</p>
                <p>&copy; @DateTime.Now.Year - Direktoratet for byggkvalitet </p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>